spring.application.name=EnterpriseCaseManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=admin
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/mydb
spring.flyway.user=admin
spring.flyway.password=12345

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.example.enterprisecasemanagementsystem=DEBUG

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

server.port=8080
server.servlet.context-path=/

spring.security.user.name=admin
spring.security.user.password=admin123
